version: '3'

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    #ports:
    #  - '6379:6379'
    expose:
      - "6379"
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  asgard-bivrost:
    build:
      context: $GOPATH/src/asgard-bivrost
      dockerfile: $GOPATH/src/asgard-bivrost/Dockerfile
    image: asgard-bivrost
    working_dir: /app
    environment:
     - APP_REGISTRY_ADDR=redis:6379
     - APP_REGISTRY_PASSWORD=
     - APP_PORT=9000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    depends_on:
      - "redis"
  bivrost-task2-service:
    build:
       context: $GOPATH/src/bivrost-task2
       dockerfile: $GOPATH/src/bivrost-task2/Dockerfile
       args:
         GITHUB_USERNAME: ${GITHUB_USERNAME}
         GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    image: bivrost-task2-service
    working_dir: /app
    environment:
    - APP_REGISTRY_ADDR=redis:6379
    - APP_REGISTRY_PASSWORD=
    - APP_PORT=9000
    - REDIS_ADDR=${REDIS_ADDR}
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    depends_on:
      - "redis"
      - "asgard-bivrost"
      - "postgres"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB_NAME: bt2
    expose:
      - "5432"
    volumes:
      - /home/koinworks/Documents/Koinworks/Document/EDP/Task_Koinworks/backup_db_bivrost_test2:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
volumes:
  redis_data:
    driver: local